name: Continuous Deployment

on:
  push:
    branches: [ main ]
  schedule:
  - cron: "0 11 * * *" # 11:00 Daily
  workflow_dispatch:

jobs:

  deployment:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 'http://syntaqx.io'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Deploy
        run: echo "TODO"
