name: Continuous Deployment

on:
  push:
    branches: [ main ]
  schedule:
  - cron: "0 11 * * *" # 11:00 Daily
  workflow_dispatch:

jobs:

  build:
    uses: ./.github/workflows/docker.yml
    with:
      push: true
    secrets: inherit

  deployment:
    needs: [ build ]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 'http://syntaqx.io'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v3
      - uses: syntaqx/setup-kustomize@main
      -
        name: Deploy
        run: |-
          kustomize edit set image syntaqx/github-flow-example=${{ needs.build.outputs.image }}
          kustomize build .
