name: Review Environment

on:
  pull_request:
    types: [ reopened, opened, synchronize ]

jobs:

  deployment:
    runs-on: ubuntu-latest
    environment:
      name: review
      url: https://${{ steps.variables.outputs.github_head_ref_slug_url }}.syntaqx.io
    steps:
      - uses: actions/checkout@v3
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        with:
          slug-maxlength: 30
      - id: variables
        run: echo "::set-output name=github_head_ref_slug_url::${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
      - name: Deploy
        run: echo "TODO"
