name: Review Environment

on:
  pull_request:
    types: [ reopened, opened, synchronize ]

jobs:

  deployment:
    runs-on: ubuntu-latest
    environment:
      name: review
      url: https://${{ steps.variables.outputs.github_base_ref_slug }}.syntaqx.io
    steps:
      - uses: actions/checkout@v3
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - id: variables
        run: echo "::set-output name=github_base_ref_slug::${{ env.GITHUB_BASE_REF_SLUG }}"
      - name: Deploy
        run: echo "TODO"
