name: Review Environment

on:
  pull_request:
    types: [ reopened, opened, synchronize ]

jobs:

  build:
    uses: ./.github/workflows/docker.yml
    with:
      push: true
    secrets: inherit

  deployment:
    needs: [ build ]
    runs-on: ubuntu-latest
    environment:
      name: review
      url: https://${{ steps.variables.outputs.github_head_ref_slug_url }}.syntaqx.io
    steps:
      - uses: actions/checkout@v3
      -
        name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        with:
          slug-maxlength: 30
      -
        name: Set outputs
        id: variables
        run: echo "::set-output name=github_head_ref_slug_url::${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
      -
        name: Setup Kustomize
        run: |-
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          mv kustomize /usr/local/bin/kustomize
          chmod +x /usr/local/bin/kustomize
      -
        name: Deploy
        run: |-
          kustomize edit set image syntaqx/github-flow-example=${{ needs.build.outputs.image }}
          kustomize build .
