name: Teardown Review Environment

on:
  pull_request:
    types: [ closed ]

jobs:

  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Deployment Environment
        uses: strumwolf/delete-deployment-environment@v2.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: review
          ref: ${{ github.head_ref }}
          onlyDeactivateDeployments: true
