name: 'Clean stale data'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '.github/workflows/stale.yml'

jobs:

  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Close Stale Issues and PRs
      - uses: actions/stale@v5

  branches:
    runs-on: ubuntu-latest
    steps:
      - name: Delete abandoned branches
        uses: phpdocker-io/github-actions-delete-abandoned-branches@v1
        id: delete_stuff
        with:
          github_token: ${{ github.token }}
          last_commit_age_days: 100
          dry_run: no
      -
        name: Get output
        run: "echo 'Deleted branches: ${{ steps.delete_stuff.outputs.deleted_branches }}'"
